[workspace]
resolver = "2"
members = [ "redis-client","redis-server"]

[workspace.package]
version = "0.0.1"
authors = ["undecidedapollo"]
description = ""
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.flame]
inherits = "release"
debug = true